#!/bin/busybox sh
#
# By Chih-Wei Huang <cwhuang@linux.org.tw>
# and Thorsten Glaser <tg@mirbsd.org>
#
# Modified by BlissLabs & Contributors
#
# License: GNU Public License
# We explicitely grant the right to use the scripts
# with Android-x86 project.
#
# shellcheck disable=SC3036,SC2068

PATH=/sbin:/bin:/system/bin:/system/xbin:/vendor/bin:/system_ext/bin:/system/vendor/bin:/system/system_ext/bin
export PATH

# configure debugging output
if [ "$DEBUG" ]; then
	LOG=/tmp/log
	set -x
else
	LOG=/dev/null
	test -e "$LOG" || busybox mknod $LOG c 1 3
fi
exec 2>>$LOG

# early boot
if test x"$HAS_CTTY" != x"Yes"; then
	# initialise /proc & /sys and /tmp
	busybox mount -t proc proc /proc
	busybox mount -t sysfs sys /sys
	busybox mount -t tmpfs tmpfs /tmp

	# let busybox install all applets as symlinks
	busybox --install -s /bin/

	# spawn shells on tty 2 and 3 if debug or install
	if [ "$DEBUG" ]; then
		# ensure they can open a controlling tty
		mknod /dev/tty c 5 0
		# create device nodes then spawn on them
		mknod /dev/tty2 c 4 2 && openvt
		mknod /dev/tty3 c 4 3 && openvt
	fi
	if [ "$DEBUG" ]; then
		echo 0 0 0 0 >/proc/sys/kernel/printk
	fi
	# initialise /dev (first time)
	busybox mount -t devtmpfs devtmpfs /dev
	mkdir -p /dev/block
	echo /bin/mdev >/proc/sys/kernel/hotplug
	mdev -s
	# re-run this script with a controlling tty
	exec env HAS_CTTY=Yes setsid cttyhack /bin/sh "$0" "$@"
fi

# now running under a controlling tty; debug output from stderr into log file
# boot up Android

# First, chmod /sbin because somehow the build process messed up the permission
chmod 755 /bin/* /sbin/*

# check if specified device has pattern like UUID= or LABEL=
find_device() {
	case "$1" in
	UUID=* | LABEL=*) busybox findfs "$1" ;;
	*) echo "$1" ;;
	esac
}

try_mount() {
	local RW=$1
	shift

	if [ "${ROOT#*:/}" != "$ROOT" ]; then
		# for NFS roots, use nolock to avoid dependency to portmapper
		mount -o $RW,noatime,nolock $@
		return $?
	fi

	case "$(blkid "$1")" in
	*TYPE=*ntfs*)
		echo "WARNING: NTFS may not work well with BlissOS. Consider using another filesystem."
		if [ "$USE_NTFS3" -ge 1 ] || [ "$BOOT_USE_NTFS3" -ge 1 ]; then
			mount -t ntfs3 -o $RW,noatime,windows_names $@
		else
			mount -t ntfs -o $RW,force $@
		fi
		;;
	*TYPE=*) mount -o $RW,noatime $@ ;;
	*) return 1 ;;
	esac
}

# "foo" as mount source is given to workaround a Busybox bug with NFS
# - as it's ignored anyways it shouldn't harm for other filesystems.
remount_rw() { mount -o remount,rw foo /mnt; }

# Debug shell no longer takes arguments anymore
debug_shell() { sh 2>&1; }

export _LAST_LOOP=0

setup_loop() {
	[ -e "$1" ] || return 1

	local base i=$_LAST_LOOP next
	while :; do
		base=/dev/loop$i
		next=$((i + 1))

		# If loop device is already set to other file
		if losetup "$base" >/dev/null 2>&1; then
			i=$next
			continue
		fi

		# If loop device fails to setup
		if ! losetup "$base" "$1" >/dev/null 2>&1; then
			i=$next
			continue
		fi

		# Assign to global variable _LAST_LOOP
		export _LAST_LOOP=$next

		ln -s "$base" /dev/block

		if [ "$2" ]; then
			mknod "$2" b 7 $((i * 16))
		else
			export RESULT=$i
		fi

		return 0
	done
}

# shellcheck disable=SC2013
for c in $(cat /proc/cmdline); do
	case "$c" in
	iso-scan/filename=*) ISO=${c##*=} ;;
	androidboot.slot_suffix=*) SLOT=${c##*=} ;;
	# androidboot.efidisk=*) EFIDISK=$(find_device "${c##*=}") ;;
	# androidboot.efidir=*) EFIDIR=${c##*=} ;;
	androidboot.mode=recovery) RCVRY=1 ;;
	*) ;;
	esac
done

# Most of the times they mislead devices in /dev with /dev/block, as
# /dev/block is used in Android (booted). So this is a workaround to
# find the correct device.
for _d in /dev/[hmnsvx][dmrv][0-9a-z]*; do
	ln -s "$_d" /dev/block/
done

[ "$SRC" ] || if [ -z "$ISO" ] && [ "$BOOT_IMAGE" ]; then
	# Avoid GRUB partition prefix
	SRC=$(dirname "${BOOT_IMAGE#*/}")
fi

# FSTAB file name
: "${FSTAB:=fstab.android}"
export FSTAB

export ROOTWAIT=${ROOTWAIT:-30}

_find_root() {
	local _root
	if [ "$ROOT" ]; then
		# Wait for ROOT to appear
		# Default to 30 sec
		for _s in $(seq 0 "$ROOTWAIT"); do
			_root=$(find_device "$ROOT")

			[ -e "$_root" ] && break
			sleep 1
		done
		export ROOT=$_root
	fi
}

_mount_root_fallback() { debug_shell fatal-err; }

export \
	find_root=_find_root \
	mount_root_fallback=_mount_root_fallback

if [ 0"$DEBUG" -gt 0 ]; then
	echo -e "\nType 'exit' to continue booting...\n"
	debug_shell debug-pre
fi

# run early scripts
for s in /scripts/early/*; do
	# shellcheck disable=SC1090
	[ -e "$s" ] && source "$s"
	type run >/dev/null && run
done

$find_root

cd /
[ ! "$ROOT" ] || ! try_mount ro "$ROOT" /mnt || $mount_root_fallback

remount_rw

export SWITCH_DEST=/android

# run scripts
for s in /scripts/mount/* /mnt/"$SRC"/scripts/*; do
	# shellcheck disable=SC1090
	[ -e "$s" ] && source "$s"
	type run >/dev/null && run
done

if [ 0"$DEBUG" -gt 1 ]; then
	echo -e "\nType 'exit' to continue booting...\n"
	debug_shell debug-found
fi

# We must disable mdev before switching to Android
# since it conflicts with Android's init
echo >/proc/sys/kernel/hotplug

# Use correct modprobe location
echo /system/bin/modprobe >/proc/sys/kernel/modprobe

export ANDROID_ROOT=/system

# run late scripts
for s in /scripts/late/*; do
	# shellcheck disable=SC1090
	[ -e "$s" ] && source "$s"
	type run >/dev/null && run
done

if [ 0"$DEBUG" -gt 2 ]; then
	echo -e "\nUse Alt-F1/F2/F3 to switch between virtual consoles"
	echo -e "Type 'exit' to enter Android...\n"

	debug_shell debug-late
fi

# Copy /tmp/log if DEBUG mode is set
[ -n "$DEBUG" ] && cp /tmp/log $SWITCH_DEST/data/bootlog.txt

# shellcheck disable=SC2093
exec ${SWITCH:-switch_root} $SWITCH_DEST /init

# avoid kernel panic
while :; do
	cat <<EOF

	Android-x86 console shell. Use only in emergencies.'

EOF
	debug_shell fatal-err
done
