#!/bin/busybox sh
#
# By Chih-Wei Huang <cwhuang@linux.org.tw>
# and Thorsten Glaser <tg@mirbsd.org>
#
# Modified by BlissLabs & Contributors
#
# License: GNU Public License
# We explicitely grant the right to use the scripts
# with Android-x86 project.
#
# shellcheck disable=SC3036,SC2068

PATH=/sbin:/bin:/system/bin:/system/xbin:/vendor/bin:/system_ext/bin:/system/vendor/bin:/system/system_ext/bin
export PATH

# ASCII art
text_art() {
	cat <<"EOF"
==========================================================

  BLISS-BASS   -   Customizable Android Subsystem for PC

==========================================================
  This product was created using Bliss-Bass	
==========================================================
EOF
}

bliss_feature() {
	if [ "$INTERNAL_MOUNT" -gt "0" ]; then
		cat <<"EOF"
# WARNING: INTERNAL_MOUNT option is enabled, all the internal partitions
# will now be recognized as USBs if the supported filesystem is available
# and will create empty directories like Android, DCIM, Documents, etc.

## DO NOT PRESS "TAP TO FIX", IT WILL FORMAT THE DRIVE!
EOF
		export REAL_FSTAB=/system/vendor/etc/fstab.internal.x86
	fi

	# Enabling AOSP features for PC
	if [ "$PC_MODE" -gt "0" ]; then
		cat <<"EOF"
# WARNING: PC_MODE will not work once Magisk or KernelSU modules are installed.
# Visit BlissOS wiki for more info & solutions
EOF
		mount --bind /system/etc/hidden_xml/pc.xml /system/etc/permissions/pc.xml
	fi

	if [ "$HPE" -gt "0" ]; then
		cat <<"EOF"
# WARNING: HPE will not work once Magisk or KernelSU modules are installed.
# Visit BlissOS wiki for more info & solutions
EOF
		mount --bind /system/etc/hidden_xml/hpe.xml /system/etc/sysconfig/hpe.xml
	fi

	# Hide bootctrl from VINTF manifest if we don't set up virtual A/B
	if ! grep androidboot.slot_suffix /proc/cmdline; then
		cat <<"EOF"
# WARNING: The system is not prepared with Virtual A/B, 
# so OTA Update will not be supported
EOF
		cat <<'EOF' >/tmp/fakeboot.xml
<?xml version="1.0" encoding="utf-8"?>
<manifest version="1.0" type="device">
</manifest>
EOF
		mount --bind /tmp/fakeboot.xml /system/vendor/etc/vintf/manifest/android.hardware.boot@1.2.xml
	fi

	# Hide BLE feature from the system
	if [ "$BT_BLE_DISABLE" -ge "1" ]; then
		cat <<EOF
# NOTICE: BLE is set to be disabled
EOF
		cat <<EOF >/tmp/noble.xml
<?xml version="1.0" encoding="utf-8"?>
<permissions>
</permissions>
EOF
		mount --bind /tmp/noble.xml /system/vendor/etc/permissions/android.hardware.bluetooth_le.xml
	fi
}

bass_data_binds() {
	# Bootanimation from data
	#
	# This change will let us place a bootanimation.zip in data/misc/bootanimation.zip
	# and if found, will bind mount it to system/media/bootanimation.zip

	if [ "$ADDON_BOOTANIMATION" -gt "0" ]; then
		cat <<"EOF"
# WARNING: ADDON_BOOTANIMATION is overriding the default bootanimation.zip
# This override might not work if you are using systemless root
EOF
		# Copy bootanimation.zip
		if [ -f /android/data/misc/bootanimation.zip ]; then
			if [ -f system/media/bootanimation.zip ]; then
				# bind mount copied bootanimation.zip to system
				mount --bind /android/data/misc/bootanimation.zip system/media/bootanimation.zip
			elif [ -f system/product/media/bootanimation.zip ]; then
				# bind mount copied bootanimation.zip to product
				mount --bind /android/data/misc/bootanimation.zip system/product/media/bootanimation.zip
			else
				cat <<"EOF"
# Bootanimation.zip not found in system/media or system/product/media
# Bootanimation.zip will not be bind mounted
EOF
			fi
		fi
	fi

	# IDC files from data
	#
	# This change will let us place idc files in data/system/devices/idc
	# and if found, will bind mount them to system/usr/idc
	#
	# /system/usr/idc/Vendor_0eef_Product_c002_Version_0111.idc
	if [ "$ADDON_IDC" -gt "0" ]; then
		cat <<"EOF"
# WARNING: ADDON_IDC is overriding idc files for this device.
# This override will not work if you are using systemless root
EOF
		find /android/data/system/devices/idc -mindepth 1 -maxdepth 1 -type f -iname '*.idc' |
			while read -r file; do
				mount --bind "$file" system/usr/idc/"$(basename "$file")"
			done
	fi

	# Allow adding to input-ports-associations.xml file using bind mount
	#
	# This will let us add known input port associations to the system without
	# recompiling the OS by passing additional hosts through an input-ports-addon.xml file.
	# How-To:
	# dumpsys SurfaceFlinger - -display-id
	# Display 4693505326422272 (HWC display 0): port=0 pnpId=DEL displayName="DELL P2314T"
	# Display 4693505326422273 (HWC display 1): port=1 pnpId=DEL displayName="DELL P2314T"
	# Display 4692921138614786 (HWC display 2): port=2 pnpId=DEL displayName="DELL S2740L"
	# Display 18309706364381699 (HWC display 3): port=3 pnpId=PHL displayName="PHL 245C5"
	# getevent -i | grep location
	# location: "usb-xhci-cdns3-1.3.4/input0"
	# location: "usb-xhci-cdns3-1.2.4/input0"
	#
	# $ adb root
	# $ adb push input-ports-addon.xml /data/misc/input-port-addon.xml
	# input-ports-addon.xml: 1 file pushed, 0 skipped. 0.0 MB/s (8 bytes in 0.000s)
	# $ cat /data/misc/input-ports-addon.xml
	# <ports>
	# 	<port display="0" input="usb-xhci-cdns3-1.1.4/input0" />
	# 	<port display="1" input="usb-xhci-cdns3-1.2.4/input0" />
	# 	<port display="2" input="usb-xhci-cdns3-1.3.4/input0" />
	# 	<port display="3" input="usb-xhci-cdns3-1.4.4/input0" />
	# 	<port display="0" input="usb-xhci-cdns3-1.4/input0" />
	# 	<port display="0" input="usb-ci_hdrc.0-1.4/input0" />
	# </ports>
	#
	# Then use the following from kernel cmdline:
	# BLISS_INPUT_PORTS_ADDON=1
	#
	# Allow adding to hosts file using bind mount
	if [ "$BLISS_INPUT_PORTS_ADDON" -gt "0" ]; then
		cat <<"EOF"
# WARNING: INPUT_PORTS_ADDON is overriding the default input-port-associations.xml file.
# This override will not work if you are using systemless root
EOF
		# bind associations file if found
		if [ -f /android/data/misc/input-port-addon.xml ]; then
			mount --bind /android/data/misc/input-port-addon.xml system/vendor/etc/input-port-associations.xml
		fi
	fi

	# init.bass-vendor.rc from data
	#
	# This change will let us place a init.bass-vendor.rc in data/vendor/etc/init/
	# and if found, will bind mount it to vendor/etc/init/init.bass-vendor.rc
	# Note: you will still want your .rc script to link to any .sh scripts from data.

	if [ "$ADDON_BASSINIT" -gt "0" ]; then
		cat <<"EOF"
# WARNING: ADDON_BASSINIT is being used to override the default Bass OS init
# This override might not work if you are using systemless root
EOF
		# bind init.bass-vendor.rc
		if [ -f /android/data/vendor/etc/init/init.bass-vendor.rc ]; then
			if [ -f vendor/etc/init/init.bass-vendor.rc ]; then
				mount --bind /android/data/vendor/etc/init/init.bass-vendor.rc vendor/etc/init/init.bass-vendor.rc
			else
				cat <<"EOF"
# init.bass-vendor.rc not found in data/vendor/etc/init/
# init.bass-vendor.rc will not be bind mounted
EOF
			fi
		fi
	fi
}

# OEM installation
if [ -n "$OEM_INSTALL" ]; then
	echo "Starting Installer"
	INSTALL=install.img # Default for Bass
fi

# configure debugging output
if [ "$DEBUG" ] || [ "$INSTALL" ] || [ "$RCVRY" ]; then
	LOG=/tmp/log
	set -x
else
	LOG=/dev/null
	test -e "$LOG" || busybox mknod $LOG c 1 3
fi
exec 2>>$LOG

# early boot
if test x"$HAS_CTTY" != x"Yes"; then
	# initialise /proc & /sys and /tmp
	busybox mount -t proc proc /proc
	busybox mount -t sysfs sys /sys
	busybox mount -t tmpfs tmpfs /tmp

	# let busybox install all applets as symlinks
	busybox --install -s /bin/

	# spawn shells on tty 2 and 3 if debug or install
	if [ "$INSTALL" ] || [ "$DEBUG" ]; then
		# ensure they can open a controlling tty
		mknod /dev/tty c 5 0
		# create device nodes then spawn on them
		mknod /dev/tty2 c 4 2 && openvt
		mknod /dev/tty3 c 4 3 && openvt
		# using chroot instead of switch_root for debugging
		export SWITCH=chroot
	fi
	if [ "$INSTALL" ] || [ "$DEBUG" ] || [ "$RCVRY" ]; then
		echo 0 0 0 0 >/proc/sys/kernel/printk
	fi
	# initialise /dev (first time)
	busybox mount -t devtmpfs devtmpfs /dev
	mkdir -p /dev/block
	echo /bin/mdev >/proc/sys/kernel/hotplug
	mdev -s
	# re-run this script with a controlling tty
	exec env HAS_CTTY=Yes setsid cttyhack /bin/sh "$0" "$@"
fi

# now running under a controlling tty; debug output from stderr into log file
# boot up Android

# First, chmod /sbin because somehow the build process messed up the permission
chmod 755 /bin/* /sbin/*

# check if specified device has pattern like UUID= or LABEL=
find_device() {
	case "$1" in
	UUID=* | LABEL=*) busybox findfs "$1" ;;
	*) echo "$1" ;;
	esac
}

try_mount() {
	local RW=$1
	shift

	if [ "${ROOT#*:/}" != "$ROOT" ]; then
		# for NFS roots, use nolock to avoid dependency to portmapper
		mount -o $RW,noatime,nolock $@
		return $?
	fi

	case "$(blkid "$1")" in
	*TYPE=*ntfs*)
		echo "WARNING: NTFS may not work well with BlissOS. Consider using another filesystem."
		if [ "$USE_NTFSPLUS" -ge 1 ] || [ "$BOOT_USE_NTFSPLUS" -ge 1 ]; then
			mount -t ntfs -o rw,force $@
		elif [ "$USE_NTFS3" -ge 1 ] || [ "$BOOT_USE_NTFS3" -ge 1 ]; then
			mount -t ntfs3 -o rw,noatime,windows_names $@
		else
			mount.ntfs-3g -o rw,force $@
		fi
		;;
	*TYPE=*) mount -o $RW,noatime $@ ;;
	*) return 1 ;;
	esac
}

check_sysroot() {
	local dev=$1 file=$2

	if try_mount ro "$dev" /mnt && [ -e /mnt/"$SRC"/$file ]; then
		ROOT=$dev
		return 0
	fi

	umount-r /mnt
	return 1
}

: ${SLEEP_SECONDS:=5}
: ${SEARCH_INTERVAL:=2}

find_sysroot_by_file() {
	local file=$1 iter=$2 dev _
	for _ in $(seq 0 "$iter"); do
		for dev in /dev/[hmnsvx][dmrv][0-9a-z]*; do
			test -e "$dev" || continue
			echo -e "Scanning $dev...\n"

			check_sysroot "$dev" "$file" || continue
			echo -e "Found at $dev\n"
			return 0
		done
		sleep $SLEEP_SECONDS
		echo -n .
	done

	echo -e "Detecting failed after $iter iterations for file $file!\n"
	return 1
}

sysroot_search() {
	cat <<EOF
Detecting Android-x86...

If it took too long to detect, reboot and check your installation folder

EOF
	local file
	for file in $ROOT_SEARCH_FILES; do
		find_sysroot_by_file "$file" "$SEARCH_INTERVAL" && return 0
		sleep $SLEEP_SECONDS
	done
	return 1
}

# "foo" as mount source is given to workaround a Busybox bug with NFS
# - as it's ignored anyways it shouldn't harm for other filesystems.
remount_rw() { mount -o remount,rw foo /mnt; }

# Debug shell no longer takes arguments anymore
debug_shell() { sh 2>&1; }

export _LAST_LOOP=0

setup_loop() {
	[ -e "$1" ] || return 1

	local base i=$_LAST_LOOP next
	while :; do
		base=/dev/loop$i
		next=$((i + 1))

		# If loop device is already set to other file
		if losetup "$base" >/dev/null 2>&1; then
			i=$next
			continue
		fi

		# If loop device fails to setup
		if ! losetup "$base" "$1" >/dev/null 2>&1; then
			i=$next
			continue
		fi

		# Assign to global variable _LAST_LOOP
		export _LAST_LOOP=$next

		ln -s "$base" /dev/block

		if [ "$2" ]; then
			mknod "$2" b 7 $((i * 16))
		else
			export RESULT=$i
		fi

		return 0
	done
}

# shellcheck disable=SC2013
for c in $(cat /proc/cmdline); do
	case "$c" in
	iso-scan/filename=*) ISO=${c##*=} ;;
	androidboot.slot_suffix=*) SLOT=${c##*=} ;;
	# androidboot.efidisk=*) EFIDISK=$(find_device "${c##*=}") ;;
	# androidboot.efidir=*) EFIDIR=${c##*=} ;;
	androidboot.mode=recovery) RCVRY=1 ;;
	*) ;;
	esac
done

if [ -z "$SRC" ]; then
	if [ -z "$ISO" ] && [ "$BOOT_IMAGE" ]; then
		# Avoid GRUB partition prefix
		SRC=$(dirname "${BOOT_IMAGE#*/}")
	fi
fi

# Most of the times they mislead devices in /dev with /dev/block, as
# /dev/block is used in Android (booted). So this is a workaround to
# find the correct device.
for _d in /dev/[hmnsvx][dmrv][0-9a-z]*; do
	ln -s "$_d" /dev/block/
done

if [ 0"$DEBUG" -gt 0 ]; then
	echo -e "\nType 'exit' to continue booting...\n"
	debug_shell debug-pre
fi

[ -d "$VTOY_PATH" ] && export HAS_VTOY=1 ROOT=/dev/mapper/ventoy

if [ "$ROOT" ]; then
	# Wait for ROOT to appear
	: ${ROOTWAIT:=30} # Default to 30 sec
	for _s in $(seq 0 $ROOTWAIT); do
		# If is booting from Ventoy GRUB2 Mode
		if [ "$HAS_VTOY" = 1 ]; then
			"$VTOY_PATH/hook/android/ventoy-disk.sh"
		else
			_root=$(find_device "$ROOT")
		fi

		[ -e "$_root" ] && break
		sleep 1
	done
	export ROOT=$_root
	unset _root
fi

# FSTAB file name
: "${FSTAB:=fstab.android}"
export FSTAB

cd /
# If there's no ROOT= specified, try to find one for 5 times
if [ ! "$ROOT" ] || ! try_mount ro "$ROOT" /mnt; then
	: "${ROOT_SEARCH_FILES:="$FSTAB ${BOOT_IMAGE#*/} system$SLOT.?fs system$SLOT.img system$SLOT/system/build.prop system/build.prop"}"

	# If is live/install mode, prior to search for $INSTALL image, default to install.sfs
	if [ "$INSTALL" ] || grep -q 'androidboot.live=true' /proc/cmdline; then
		ROOT_SEARCH_FILES="${INSTALL:-install.sfs} $ROOT_SEARCH_FILES"
	fi

	# If is booting from iso/loopback
	if [ "$ISO" ]; then
		ROOT_SEARCH_FILES="$ISO $ROOT_SEARCH_FILES"
	fi

	sysroot_search
fi || debug_shell fatal-err

remount_rw

if [ "$ISO" ]; then
	mount -o loop "/mnt/$SRC/$ISO" /mnt
fi
# If install is specified, but no install image found (probably wont happend)
# Will be deprecated
if [ "$INSTALL" ] && [ ! -f "/mnt/$SRC/$INSTALL" ]; then
	debug_shell fatal-err
fi

# Most of the times they mislead devices in /dev with /dev/block, as
# /dev/block is used in Android (booted). So this is a workaround to
# find the correct device.
for _d in /dev/[hmnsvx][dmrv][0-9a-z]*; do
	ln -s "$_d" /dev/block/
done

if [ 0"$DEBUG" -gt 0 ]; then
	echo -e "\nType 'exit' to continue booting...\n"
	debug_shell debug-pre
fi

[ -d "$VTOY_PATH" ] && export HAS_VTOY=1 ROOT=/dev/mapper/ventoy

if [ "$ROOT" ]; then
	# Wait for ROOT to appear
	: ${ROOTWAIT:=30} # Default to 30 sec
	for _s in $(seq 0 $ROOTWAIT); do
		# If is booting from Ventoy GRUB2 Mode
		if [ "$HAS_VTOY" = 1 ]; then
			"$VTOY_PATH/hook/android/ventoy-disk.sh"
		else
			_root=$(find_device "$ROOT")
		fi

		[ -e "$_root" ] && break
		sleep 1
	done
	export ROOT=$_root
	unset _root
fi

# FSTAB file name
: "${FSTAB:=fstab.android}"
export FSTAB

cd /
# If there's no ROOT= specified, try to find one for 5 times
if [ ! "$ROOT" ] || ! try_mount ro "$ROOT" /mnt; then
	: "${ROOT_SEARCH_FILES:="$FSTAB ${BOOT_IMAGE#*/} system$SLOT.?fs system$SLOT.img system$SLOT/system/build.prop system/build.prop"}"

	# If is live/install mode, prior to search for $INSTALL image, default to install.sfs
	if [ "$INSTALL" ] || grep -q 'androidboot.live=true' /proc/cmdline; then
		ROOT_SEARCH_FILES="${INSTALL:-install.sfs} $ROOT_SEARCH_FILES"
	fi

	# If is booting from iso/loopback
	if [ "$ISO" ]; then
		ROOT_SEARCH_FILES="$ISO $ROOT_SEARCH_FILES"
	fi

	sysroot_search
fi || debug_shell fatal-err

remount_rw

if [ "$ISO" ]; then
	mount -o loop "/mnt/$SRC/$ISO" /mnt
fi
# If install is specified, but no install image found (probably wont happend)
# Will be deprecated
if [ "$INSTALL" ] && [ ! -f "/mnt/$SRC/$INSTALL" ]; then
	debug_shell fatal-err
fi

hash -r
text_art

if ! grep 'sse4_2' /proc/cpuinfo 1>/dev/null; then
	echo 'WARNING: Your CPU does not support SSE4.2 instructions, the OS will not boot'
fi

if [ "$RCVRY" ]; then
	MODE_BASE=/recovery
elif [ "$INSTALL" ]; then
	MODE_BASE=/install
else
	MODE_BASE=/android
fi
export MODE_BASE

# load scripts
for s in /scripts/* /mnt/"$SRC"/scripts/*; do
	# shellcheck disable=SC1090
	test -e "$s" && source "$s"
done

if [ "$COPYTORAM" ] && [ "$COPYTORAM" != false ]; then
	copy_to_ram
fi

setup_recovery || debug_shell fatal-err
check_fstab
process_fstab

# If neither RCVRY nor INSTALL is specified
[ "$RCVRY" ] || [ "$INSTALL" ] || bliss_feature

probe_recovery

if [ 0"$DEBUG" -gt 1 ]; then
	echo -e "\nType 'exit' to continue booting...\n"
	debug_shell debug-found
fi

# # A target should provide its detect_hardware function.
# # On success, return 0 with the following values set.
# # return 1 if it wants to use auto_detect
# [ "$AUTO" != 1 ] && detect_hardware && FOUND=1

[ "$INSTALL" ] && setup_install

link_fstab

mount_recovery
setup_tslib
setup_dpi
post_detect
post_setup_recovery

if [ 0"$DEBUG" -gt 2 ]; then
	echo -e "\nUse Alt-F1/F2/F3 to switch between virtual consoles"
	echo -e "Type 'exit' to enter Android...\n"

	debug_shell debug-late
fi

if [ "$INSTALL" ]; then
	INITRD_BOOTLOG=/install/bootlog.txt
else
	# We must disable mdev before switching to Android
	# since it conflicts with Android's init
	echo >/proc/sys/kernel/hotplug

	# Use correct modprobe location
	echo /system/bin/modprobe >/proc/sys/kernel/modprobe

	INITRD_BOOTLOG=/android/data/bootlog.txt

	# Load data bind mounts
	# This requires /data to be mounted
	if [ "$DATA_BLK" ]; then
		blk=${DATA_BLK%%:*}
		fs=${DATA_BLK#*:}
		fs=${fs%%:*}
		opt=${DATA_BLK##*:}
		mount ${fs:+-t "$fs"} ${opt:+-o "$opt"} "$blk" /android/data
	fi
	bass_data_binds
fi

[ -n "$DEBUG" ] && cp /tmp/log "$INITRD_BOOTLOG"

export ANDROID_ROOT=/system

# shellcheck disable=SC2093
exec "${SWITCH:-switch_root}" $MODE_BASE /init

# avoid kernel panic
while :; do
	cat <<EOF

	Android-x86 console shell. Use only in emergencies.'

EOF
	debug_shell fatal-err
done
